name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for SonarQube analysis

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Change if your project uses a different version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Run tests and generate coverage report
      - name: Run tests with coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=./ --cov-report=xml

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
