name: Security Scan

on: [push, pull_request]

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies and start FastAPI app
        run: |
          pip install -r requirements.txt
          nohup uvicorn insecure_app:app --host 0.0.0.0 --port 8000 & 
          sleep 15  # Wait for FastAPI to start

      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: http://localhost:8000/docs
          cmd_options: -m 5 -T 600 -j
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          artifact_name: zap_scan_report

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap_scan_report
          path: zap-report.html
